apiVersion: v2
name: irsa-app
description: IRSA claim instance values for GitOps
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: crossplane-irsa-claim
    version: "0.1.0"
    repository: "file://../../plataforma/helm-charts/crossplane-irsa-claim"
