apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
    policies.kyverno.io/title: Disallow latest image tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod, Deployment
spec:
  validationFailureAction: Audit
  emitWarning: true
  background: true
  rules:
    - name: check-image-tag-deployment
      match:
        any:
          - resources:
              kinds:
                - Deployment
              namespaces:
                - app
      validate:
        message: "Using ':latest' image tags is not allowed."
        foreach:
          - list: "request.object.spec.template.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ contains(element.image, ':latest') }}"
                    operator: Equals
                    value: true
    - name: check-image-tag-pod
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - app
      validate:
        message: "Using ':latest' image tags is not allowed."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ contains(element.image, ':latest') }}"
                    operator: Equals
                    value: true
