apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: rds.aws.platform.lab
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    platform.lab/provider: aws
spec:
  compositeTypeRef:
    apiVersion: platform.lab/v1alpha1
    kind: XRDS
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: db-instance
            base:
              apiVersion: rds.aws.upbound.io/v1beta1
              kind: Instance
              spec:
                deletionPolicy: Orphan
                forProvider:
                  allocatedStorage: 20
                  engine: postgres
                  engineVersion: "16"
                  instanceClass: db.t3.micro
                  dbName: garagem
                  username: appuser
                  publiclyAccessible: false
                  skipFinalSnapshot: true
                  autoMinorVersionUpgrade: true
                  passwordSecretRef:
                    namespace: app
                    name: ""
                    key: password
                  region: us-east-1
                  tags: {}
                providerConfigRef:
                  name: default
            connectionDetails:
              - name: host
                type: FromFieldPath
                fromFieldPath: status.atProvider.address
              - name: port
                type: FromFieldPath
                fromFieldPath: status.atProvider.port
              - name: username
                type: FromFieldPath
                fromFieldPath: spec.forProvider.username
              - name: database
                type: FromFieldPath
                fromFieldPath: spec.forProvider.dbName
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.name
                toFieldPath: metadata.annotations[crossplane.io/external-name]
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.region
                toFieldPath: spec.forProvider.region
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.engine
                toFieldPath: spec.forProvider.engine
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.engineVersion
                toFieldPath: spec.forProvider.engineVersion
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.instanceClass
                toFieldPath: spec.forProvider.instanceClass
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.allocatedStorage
                toFieldPath: spec.forProvider.allocatedStorage
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.dbName
                toFieldPath: spec.forProvider.dbName
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.username
                toFieldPath: spec.forProvider.username
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.passwordSecretName
                toFieldPath: spec.forProvider.passwordSecretRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.passwordSecretNamespace
                toFieldPath: spec.forProvider.passwordSecretRef.namespace
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.publiclyAccessible
                toFieldPath: spec.forProvider.publiclyAccessible
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.skipFinalSnapshot
                toFieldPath: spec.forProvider.skipFinalSnapshot
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.deletionPolicy
                toFieldPath: spec.deletionPolicy
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.providerConfigRefName
                toFieldPath: spec.providerConfigRef.name
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.tags
                toFieldPath: spec.forProvider.tags
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.address
                toFieldPath: status.endpoint
              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.port
                toFieldPath: status.port
              - type: ToCompositeFieldPath
                fromFieldPath: spec.forProvider.dbName
                toFieldPath: status.dbName
