claim:
  name: app-s3-policy
  namespace: app
  description: S3 access policy for app workload
  path: "/"
  deletionPolicy: Orphan
  providerConfigRefName: default
  # Optional:
  # - If informed, this string is sent as-is to Crossplane.
  # - If empty, the chart generates policyDocument from bucketName + actions.
  policyDocument: ""
  bucketName: app-storage
  bucketActions:
    - s3:ListBucket
  objectActions:
    - s3:GetObject
    - s3:PutObject
    - s3:DeleteObject
  tags: {}
