app-template:
  replicaCount: 2
  image:
    repository: david210/lab-api-carro
    tag: latest
  service:
    port: 80
  env:
    - name: API_URL
      value: "http://api-carro-svc:80/carros"
    - name: FLASK_DEBUG
      value: "true" 