apiVersion: v2
name: iam-policy-app
description: IAM policy claim instance values for GitOps
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: crossplane-iam-policy-claim
    version: "0.1.0"
    repository: "file://../../plataforma/helm-charts/crossplane-iam-policy-claim"
