crossplane-iam-policy-claim:
  claim:
    name: api-storage-policy
    namespace: app
    description: S3 access policy for api workload
    path: "/"
    deletionPolicy: Orphan
    providerConfigRefName: default
    bucketName: api-storage
    bucketActions:
      - s3:ListBucket
    objectActions:
      - s3:GetObject
      - s3:PutObject
      - s3:DeleteObject
    tags:
      owner: api
      environment: eks
