claim:
  name: app-s3-irsa
  namespace: app
  serviceAccountNamespace: app
  serviceAccountName: api-carro
  policyName: "app-s3-irsa-policy"
  policyDocument: ""
  policyDescription: "Managed policy for IRSA workload"
  policyPath: "/"
  bucketName: ""
  bucketActions:
    - s3:ListBucket
  objectActions:
    - s3:GetObject
    - s3:PutObject
    - s3:DeleteObject
  deletionPolicy: Orphan
  providerConfigRefName: default
  tags: {}
