apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.claim.passwordSecretName }}
  namespace: {{ .Values.claim.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
stringData:
  {{ .Values.claim.passwordSecretKey }}: {{ .Values.claim.password | quote }}
---
apiVersion: platform.lab/v1alpha1
kind: RDS
metadata:
  name: {{ .Values.claim.name }}
  namespace: {{ .Values.claim.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  writeConnectionSecretToRef:
    name: {{ .Values.claim.connectionSecretName | default (printf "%s-conn" .Values.claim.name) | quote }}
  parameters:
    name: {{ .Values.claim.name | quote }}
    region: {{ .Values.claim.region | quote }}
    engine: {{ .Values.claim.engine | quote }}
    engineVersion: {{ .Values.claim.engineVersion | quote }}
    instanceClass: {{ .Values.claim.instanceClass | quote }}
    allocatedStorage: {{ .Values.claim.allocatedStorage }}
    dbName: {{ .Values.claim.dbName | quote }}
    username: {{ .Values.claim.username | quote }}
    passwordSecretName: {{ .Values.claim.passwordSecretName | quote }}
    passwordSecretNamespace: {{ .Values.claim.namespace | quote }}
    publiclyAccessible: {{ .Values.claim.publiclyAccessible }}
    skipFinalSnapshot: {{ .Values.claim.skipFinalSnapshot }}
    deletionPolicy: {{ .Values.claim.deletionPolicy | quote }}
    providerConfigRefName: {{ .Values.claim.providerConfigRefName | quote }}
    tags:
{{- toYaml .Values.claim.tags | nindent 6 }}
