crossplane-s3-claim:
  claim:
    name: api-storage
    namespace: app
    connectionSecretName: api-storage-conn
    region: us-east-1
    deletionPolicy: Orphan
    providerConfigRefName: default
    tags:
      owner: api
      environment: eks

crossplane-irsa-claim:
  claim:
    name: api-storage-irsa
    namespace: app
    serviceAccountNamespace: app
    serviceAccountName: api-carro
    policyName: "api-storage-irsa-policy-v2"
    policyDocument: ""
    policyDescription: "S3 access policy for api workload"
    policyPath: "/"
    bucketName: "api-storage-*"
    bucketActions:
      - s3:ListBucket
    objectActions:
      - s3:GetObject
      - s3:PutObject
      - s3:DeleteObject
    deletionPolicy: Orphan
    providerConfigRefName: default
    tags:
      owner: api
      environment: eks

crossplane-rds-claim:
  claim:
    name: api-garagem-db
    namespace: app
    connectionSecretName: api-garagem-db-conn
    passwordSecretName: api-garagem-db-auth
    passwordSecretKey: password
    password: "TroqueEssaSenhaNoLab123!"
    region: us-east-1
    engine: postgres
    engineVersion: "16"
    instanceClass: db.t3.micro
    allocatedStorage: 20
    dbName: garagem
    username: appuser
    publiclyAccessible: false
    skipFinalSnapshot: true
    deletionPolicy: Orphan
    providerConfigRefName: default
    tags:
      owner: api
      environment: eks
