apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: 'https://github.com/DavidFerreira21/lab-plataform-engineering.git'
      targetRevision: HEAD
      path: plataforma/crossplane/base
    - repoURL: 'https://github.com/DavidFerreira21/lab-plataform-engineering.git'
      targetRevision: HEAD
      path: plataforma/crossplane/xrd
    - repoURL: 'https://github.com/DavidFerreira21/lab-plataform-engineering.git'
      targetRevision: HEAD
      path: plataforma/crossplane/compositions
    - repoURL: 'https://github.com/DavidFerreira21/lab-plataform-engineering.git'
      targetRevision: HEAD
      path: plataforma/cluster-metadata
      helm:
        releaseName: platform-cluster-metadata
        valueFiles:
          - values.yaml
    - repoURL: 'https://github.com/DavidFerreira21/lab-plataform-engineering.git'
      targetRevision: HEAD
      path: gitops/storage-s3
      helm:
        releaseName: platform-storage-s3
        valueFiles:
          - values.yaml
    - repoURL: 'https://github.com/DavidFerreira21/lab-plataform-engineering.git'
      targetRevision: HEAD
      path: gitops/app
      helm:
        releaseName: platform-api
        valueFiles:
          - values-eks.yaml
    - repoURL: 'https://github.com/DavidFerreira21/lab-plataform-engineering.git'
      targetRevision: HEAD
      path: gitops/web
      helm:
        releaseName: platform-web
        valueFiles:
          - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
