apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-core
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: "https://github.com/DavidFerreira21/lab-plataform-engineering.git"
      targetRevision: HEAD
      path: plataforma/crossplane/base
    - repoURL: "https://github.com/DavidFerreira21/lab-plataform-engineering.git"
      targetRevision: HEAD
      path: plataforma/crossplane/xrd
    - repoURL: "https://github.com/DavidFerreira21/lab-plataform-engineering.git"
      targetRevision: HEAD
      path: plataforma/crossplane/compositions
    - repoURL: "https://github.com/DavidFerreira21/lab-plataform-engineering.git"
      targetRevision: HEAD
      path: plataforma/cluster-metadata
      helm:
        releaseName: platform-cluster-metadata
        valueFiles:
          - values.yaml
    - repoURL: "https://github.com/DavidFerreira21/lab-plataform-engineering.git"
      targetRevision: HEAD
      path: plataforma/kyverno
  destination:
    server: "https://kubernetes.default.svc"
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
