{{- $sa := .Values.serviceAccount | default dict -}}
{{- if $sa.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-template.serviceAccountName" . | quote }}
{{- if $sa.annotations }}
  annotations:
{{ toYaml $sa.annotations | indent 4 }}
{{- end }}
{{- end }}
