apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws-irsa
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  serviceAccountTemplate:
    metadata:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::917246193838:role/eks-dev-crossplane-irsa-role
