apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xiampolicies.platform.lab
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  group: platform.lab
  names:
    kind: XIAMPolicy
    plural: xiampolicies
  claimNames:
    kind: IAMPolicy
    plural: iampolicies
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                    policyDocument:
                      type: string
                    description:
                      type: string
                      default: "Managed policy for platform workloads"
                    path:
                      type: string
                      default: "/"
                    deletionPolicy:
                      type: string
                      default: Orphan
                      enum:
                        - Orphan
                        - Delete
                    providerConfigRefName:
                      type: string
                      default: default
                    tags:
                      type: object
                      additionalProperties:
                        type: string
                  required:
                    - name
                    - policyDocument
              required:
                - parameters
            status:
              type: object
              properties:
                policyArn:
                  type: string
                policyName:
                  type: string
