apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
{{- if .Values.env }}
          env:
{{ toYaml .Values.env | indent 12 }}
{{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort | default .Values.service.port }}
