claim:
  name: app-db
  namespace: app
  connectionSecretName: ""
  passwordSecretName: app-db-auth
  passwordSecretKey: password
  password: ""
  region: us-east-1
  engine: postgres
  engineVersion: "16"
  instanceClass: db.t3.micro
  allocatedStorage: 20
  dbName: garagem
  username: appuser
  publiclyAccessible: false
  skipFinalSnapshot: true
  deletionPolicy: Orphan
  providerConfigRefName: default
  tags: {}
