crossplane-s3-claim:
  claim:
    name: api-storage
    namespace: app
    region: us-east-1
    deletionPolicy: Orphan
    providerConfigRefName: default
    tags:
      owner: api
      environment: eks
