apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/DavidFerreira21/lab-plataform-engineering.git'
    targetRevision: HEAD
    path: app/api
    helm: # Adicione este bloco para forçar o motor do Helm
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app # Onde seus apps vão morar
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true