app-template:
  replicaCount: 1
  image:
    repository: david210/lab-web-carro # Imagem do Front-end
    tag: latest
  service:
    port: 80        
    targetPort: 5000
    name: web-carro
  ingress:
    enabled: true
    host: web.local
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  env:
    - name: API_URL
      value: "http://api-carro:80/carros"
  probes:
    enabled: true
    readiness:
      path: /healthz
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 5
    liveness:
      path: /healthz
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 5
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
