app-template:
  replicaCount: 1
  image:
    repository: david210/lab-web-carro # Imagem do Front-end
    tag: latest
  service:
    port: 80        
    targetPort: 5000
  ingress:
    enabled: true
    host: web.local