{{- $base := printf "/%s/%s" (trimPrefix "/" .Values.externalSecret.metadataPrefix) .Values.externalSecret.clusterName -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.externalSecret.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.store.name }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: oidcProviderArn
      remoteRef:
        key: {{ printf "%s/oidc/provider_arn" $base | quote }}
    - secretKey: oidcIssuerHostpath
      remoteRef:
        key: {{ printf "%s/oidc/issuer_hostpath" $base | quote }}
    - secretKey: accountId
      remoteRef:
        key: {{ printf "%s/account/id" $base | quote }}
{{- if .Values.s3BucketSecret.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.s3BucketSecret.name }}
  namespace: {{ .Values.s3BucketSecret.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  refreshInterval: {{ .Values.s3BucketSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.store.name }}
  target:
    name: {{ .Values.s3BucketSecret.name }}
    creationPolicy: Owner
    template:
      data:
        bucketName: {{ printf "%s-%s-%s" .Values.s3BucketSecret.bucketPrefix .Values.store.region "{{ .accountId }}" | quote }}
  data:
    - secretKey: accountId
      remoteRef:
        key: {{ printf "%s/account/id" $base | quote }}
{{- end }}
