app-template:
  serviceAccount:
    create: true
    name: api-carro
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::590183676219:role/api-storage-irsa"
  replicaCount: 1
  image:
    repository: david210/lab-api-carro
    tag: latest
  service:
    port: 80
    targetPort: 8000
    name: api-carro-svc
  env:
    - name: S3_ENDPOINT
      value: "https://s3.us-east-1.amazonaws.com"
    - name: S3_BUCKET
      valueFrom:
        secretKeyRef:
          name: "api-storage-conn"
          key: "bucketName"
    - name: S3_ACCESS_KEY
      value: ""
    - name: S3_SECRET_KEY
      value: ""
    - name: S3_REGION
      value: "us-east-1"
    - name: S3_USE_SSL
      value: "true"
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: "api-garagem-db-conn"
          key: "host"
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: "api-garagem-db-conn"
          key: "port"
    - name: DB_NAME
      value: "garagem"
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: "api-garagem-db-conn"
          key: "username"
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: "api-garagem-db-auth"
          key: "password"
    - name: API_URL
      value: "http://api-carro-svc:80/carros"
    - name: FLASK_DEBUG
      value: "true"

  ingress:
    enabled: false
    host: api.local
  probes:
    enabled: true
    readiness:
      path: /healthz
      initialDelaySeconds: 20
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 5
    liveness:
      path: /healthz
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 5
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
