name: API DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/api/**'

jobs:
  security-sast:
    name: Security Analysis (SAST) - API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit (SAST)
        run: bandit -r app/api -ll

  build-and-sca:
    name: Build and SCA Scan - API
    needs: security-sast
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Buildpacks
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/lab-api-carro
          # Vamos usar o SHA curto para facilitar
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Build gerando a tag de versão
          pack build $IMAGE_NAME:$SHORT_SHA \
            --path app/api \
            --builder gcr.io/buildpacks/builder:v1
          
          # Criamos a tag latest LOCALMENTE para o Trivy não se perder
          docker tag $IMAGE_NAME:$SHORT_SHA $IMAGE_NAME:latest

      - name: Run Trivy (SCA & Image Scan)
        uses: aquasecurity/trivy-action@master
        with:
          # Escaneamos a 'latest' que acabamos de marcar localmente
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/lab-api-carro:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Push Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/lab-api-carro
          SHORT_SHA=$(git rev-parse --short HEAD)
          
          # Sobe a versão específica e a latest
          docker push $IMAGE_NAME:$SHORT_SHA
          docker push $IMAGE_NAME:latest