name: Web DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/web/**'

jobs:
  security-sast:
    name: Security Analysis (SAST) - Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit (SAST)
        # O Bandit vai analisar o código Flask
        run: bandit -r app/web -ll

  requirements:
    name: Requirements (Helm) - Web
    needs: security-sast
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Build Helm dependencies
        run: helm dependency build app/web

      - name: Verify Helm artifacts are committed
        run: |
          git diff --exit-code app/web/Chart.lock app/web/charts || {
            echo "Helm dependencies changed. Commit app/web/Chart.lock and app/web/charts/*.tgz";
            exit 1;
          }

  build-and-sca:
    name: Build and SCA Scan - Web
    needs: requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build with Buildpacks
        run: |
          # Define o nome da imagem e a tag (SHA curto)
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/lab-web-carro
          VERSION=v${{ github.run_number }}
          
          echo "Building version: $VERSION"
          
          # Build local sem --publish para o Trivy poder escanear
          pack build $IMAGE_NAME:$VERSION \
            --path app/web \
            --builder gcr.io/buildpacks/builder:v1

          # Cria a tag latest localmente para conveniência
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:latest

      - name: Run Trivy (SCA & Image Scan)
        uses: aquasecurity/trivy-action@master
        with:
          # Escaneamos a imagem recém-criada (usando o SHA curto)
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/lab-web-carro:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Push Web Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/lab-web-carro
          VERSION=v${{ github.run_number }}
          
          # Envia ambas as tags para o Docker Hub
          docker push $IMAGE_NAME:$VERSION
          docker push $IMAGE_NAME:latest
