name: Web DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/web/**'

jobs:
  web:
    # Wrapper: chama o workflow reutilizável com os parâmetros da Web
    uses: ./.github/workflows/python-app-template.yml
    with:
      # Caminho da aplicação
      app_path: app/web
      # Nome da imagem no Docker Hub (sem usuário)
      image_name: lab-web-carro
    secrets:
      # Credenciais do Docker Hub
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
